# Generated by Django 5.2.5 on 2025-09-15 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('baju', 'Baju'), ('celana', 'Celana'), ('sepatu', 'Sepatu'), ('topi', 'Topi'), ('kaus kaki', 'Kaus kaki'), ('sarung tangan', 'Sarung tangan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
