# Generated by Django 5.2.5 on 2025-09-11 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_brand_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('baju', 'Baju'), ('celana', 'Celana'), ('sepatu', 'Sepatu'), ('topi', 'Topi'), ('kaus kaki', 'Kaus kaki'), ('sarung tangan', 'Sarung tangan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
